### PR TITLE
Move to statusline

### PR DESCRIPTION
**Pull request by Chris2011**
Moved to the statusbar instead of the toolbar.

### CODE REVIEW

**Comment by junichi11** [comment]
Please don't change the line ending type. It is changed in your changes.

**Comment by Chris2011** [comment]
Ok sry for that, should I revert it or what?

**Comment by Chris2011** [comment]
I will be aware of it next time.

**Comment by junichi11** [comment]
Probably, last two commits are not needed. I prefer reset because there are no changes after them. You can remove the remote branch once. Then
- Run proper `reset` command in your local branch 
- Check diff
- Push your branch to your remote repository

**Comment by Chris2011** [comment]
I reset to only the implementation. I tested it and it still works. I removed some unused code ActionReferences, because there was still a button in the toolbar. Please review it.

**Comment by Chris2011** [comment]
Anything new here?

**Comment by junichi11** [comment]
Sorry to be late. 
I remembered why I didn't add it to the status bar. Maybe, the Combobox is not proper. So I prefer another implementation. Probably, I'll try it if I can make time for it.

**Comment by Chris2011** [comment]
Yes I understand that and I know that, but the mainintention was to bring it to the bottom, because of, not everyone is using the toolbar, me not too. So I think for the first version it is acceptable, because the statusbar is always there.

I don't like the dropDownList too, because you can't search in there only from typing a character but I think smth like this, would be better:

encoding-control

The control looks more lightweight. Maybe it is not needed to open it like this, maybe yes. It could be a good design pattern for NB. But I think a little, decoupled list on the right corner, above the button to choose the encoding AND to have a dedicated search-field inside of it, would be great.

What do you think?

**Comment by junichi11** [comment]
I've fixed it.
https://github.com/junichi11/netbeans-encoding-plugin/releases/tag/v1.4.0

**Comment by Chris2011** [comment]
image

Unfortunately it doesn't look well.

**Comment by junichi11** [comment]
It seems that this problem occurs in Windows. I added it as a new issue #17.

**Comment by Chris2011** [comment]
Ok thx.

**Comment by Chris2011** [comment]
It works. Thx.

**Comment by junichi11** [comment]
> It works. Thx.

Sure. Thank you for your verification!

**Pull request closed without merging**
