### PR TITLE
Move to statusline

### PR DESCRIPTION
**Pull request by Chris2011**
I implemented the thing that the combo box is inside the statusline. Why? The thing is I think someone, like me will not use the toolbar, because I hided it from the IDE to get more space. The statusline is always there. You can't hide it by default. Maybe with another code but in general you can't.

So I decided to add it to the statusline, maybe we should talk about an option to say, set it to toolbar or statusline that everyone can choose by there own.

### CODE REVIEW

**Comment by junichi11** [comment]
I've created the `nb82` branch. So, please change the branch to `junichi11:nb82`. Sorry for the inconvenience.

**Comment by Chris2011** [comment]
No problem, I will do it later. thx.

**Comment by Chris2011** [comment]
I merged nb82 into the move-to-statusline. Please have a look. Thx.

**Comment by junichi11** [comment]
> I merged nb82 into the move-to-statusline

It's not that. It meant not "merging the branch" but "changing it".

nb-encoding-pr12

Thanks.

**Comment by Chris2011** [comment]
So you mean, that I have to move my stuff, that I changed to that branch?

**Comment by Chris2011** [comment]
Or do a new pull request with my branch to nb82?

**Comment by junichi11** [comment]
> Or do a new pull request with my branch to nb82?

Yes. Simply, you can recreate a new PR to nb82. Thanks.

**Comment by Chris2011** [comment]
Closed in case of this PR: #13

**Pull request closed without merging**
