### PR TITLE
QA & + languages

### PR DESCRIPTION
**Pull request by javatlacati**
Please review it.

Regards.

### CODE REVIEW

**Comment by junichi11** [comment]
Sorry, I'll close this PR. Could you send them as new PRs again after you have a look at the following?

- Please don't send all changes at once. (Separate code and localization changes)
- Please don't change the format(just follow the existing format).
- Please don't send your PRs to the master branch.(please send them to the `nb81` branch)

Thanks.

**Comment by javatlacati** [comment]
wasn't the nb81 branch already integrated?

**Comment by junichi11** [comment]
nb81 is the branch for development. Generally, I think that you should not send a PR to the master branch if a repository has multiple branches. Sorry, I'll add CONTRIBUTING file later because this repository does not have it now.

**Comment by javatlacati** [comment]
and you can change the name to development (I suggest) :P

**Comment by junichi11** [comment]
> and you can change the name to development (I suggest) :P

Sorry, I don't do it.

**Pull request closed without merging**
