### PR TITLE
#14 - Extend jfilechooser

### PR DESCRIPTION
**Pull request by Chris2011**
This PR will handle #14.

* Removed the DropDownList from the right.
* Added DropDownList below the others for a better UX/UI.

### CODE REVIEW

**Comment by junichi11** [comment]
I'm working on another module with time limit now. So I cannot review your PRs soon, sorry. I'll look at them after I finish it :)

Thanks for your understanding.

**Comment by Chris2011** [comment]
Anything new here?

**Comment by junichi11** [comment]
I got the following error:
```
SEVERE [global]
java.lang.ArrayIndexOutOfBoundsException: No such child: 2
	at java.awt.Container.getComponent(Container.java:334)
	at com.junichi11.netbeans.modules.encoding.ui.EncodingJFileChooser.addEncodingComboBox(EncodingJFileChooser.java:88)
	at com.junichi11.netbeans.modules.encoding.ui.EncodingJFileChooser.<init>(EncodingJFileChooser.java:73)
	at com.junichi11.netbeans.modules.encoding.actions.SaveInEncoding.performAction(SaveInEncoding.java:44)
	at org.openide.util.actions.NodeAction.performAction(NodeAction.java:295)
	at org.openide.util.actions.CallableSystemAction$1.run(CallableSystemAction.java:130)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.util.actions.CallableSystemAction.actionPerformed(CallableSystemAction.java:127)
	at org.openide.util.actions.NodeAction.actionPerformed(NodeAction.java:283)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Chris2011** [comment]
Hm ok, I will have a look later. Thx.

**Comment by Chris2011** [comment]
Hey @junichi11 can you tell me, when you exactly this Exception?

**Comment by junichi11** [comment]
- Select a file
- Click `File > Open in Encoding...`

**Comment by Chris2011** [comment]
Hm ok, will test it again, couldn't reproduce it yesterday.

**Comment by Chris2011** [comment]
Is this a file action? I only see it under the Menu -> File -> Open in Encoding, but not when I select a file.

**Comment by Chris2011** [comment]
image

**Comment by Chris2011** [comment]
And when I open use the menu -> file -> open in encoding, everything is fine.

**Comment by junichi11** [comment]
I tried implementing because I got the same error.

**Pull request closed without merging**
